# -*- coding: utf-8 -*-
"""fix_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iwd8k8T8idl4QXRtq3f1a9_12W6JBZzy
"""

import nbformat

notebooks = [
    "Automotive_NLP_Practicas_(2).ipynb",
    "Baby_NLP_Practicas (3).ipynb"
]

for path in notebooks:
    print(f"Processing {path}...")

    nb = nbformat.read(path, as_version=4)

    # Remove widget metadata if exists
    if "widgets" in nb.metadata:
        nb.metadata.pop("widgets", None)

    nbformat.write(nb, path)
    print(f"Notebook fixed: {path}")